version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 88:80
    volumes:
      - './src:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
  db:
    container_name: db
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
  php:
    container_name: php
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/var/www/html'
    depends_on:
      - db
    environment:
      - MYSQL_USER=$MYSQL_USER
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db