version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 88:80
    volumes:
      - './src:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
  db:
    container_name: db
    image: mysql:8
    environment:
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/var/www/html'
    depends_on:
      - db
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db